services:
  postgres:
    image: postgis/postgis:16-3.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER:  guia_admin
      POSTGRES_PASSWORD:  guiapassw
      POSTGRES_DB:  guia_turistica
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  optimizer:
    build: ./optimizer
    ports:
      - "8000:8000"
  
volumes:
  postgres_data:
